### ISSUE TITLE
7 secondes de silence en début de AU18a9

### ISSUE THREAD

**Issue by PhilJRS** [PhilJRS/dtars#14]
Il y a 7 secondes de silence en début de AU18a9.
1) corriger le média en question avec Wondershare
2) le ranger directement dans WD/Collections/AU/

**Comment by BSCH67** [comment]
OK c'est coupé et rangé. Le petit plus, l'icône (2 croches) a changé au profit de la jaquette du disque. Mais je n'ai rien fait pour...la jaquette du 33T s'est accrochée sans demandée son reste !
