### ISSUE TITLE
Titres du 33t DTA

### ISSUE THREAD

**Issue by PhilJRS** [PhilJRS/dtars#20]
Probablement dû aux techniques de collectes encore peu formelles des débuts, les titres du  DTA76 ont été mal saisis.  Notamment, il y a souvent 2 titres par morceau parfois même 3 qui doivent être repris, par ex
"Branle simple coupé_Noël des bergers de Ballersdorf_Hirtereige vo Ballersdorf_ "

**Comment by PhilJRS** [comment]
faire une màj du sheet DTA de BS/PS

**Comment by BSCH67** [comment]
Après màj et 1ère constatations, il faut considérer que, parfois, les doubles titres sont redondant. Il faut vraiment valider titre par titre ceux qui ont une vrai valeur ajoutée.

**Comment by PhilJRS** [comment]
Merci de la collecte, en colonne E de BSPS,mais je suis bien d'accord que les n° 3, 4, 6, 12 redondent plus que de besoin  
Y a-t-il eu une passe sur les titres sur le dernier CD?
