### ISSUE TITLE
JBW 

### ISSUE THREAD

**Issue by BSCH67** [PhilJRS/dtars#24]
3 liens "M" qui ne s'ouvrent pas :
JBW2p86 
JBW2p116
JBW2p244

**Comment by PhilJRS** [comment]
Ces 3 liens semblent avoir changé .  J'ai recherché sous https://www.aepem.com/recherche-biblio/?rb=WeckerlinA-2-244
puis j'ai corrigé dans gold/JBW l'attribut  "urlM": de la ref  en _2-086 et 88_, (pas juste _2-086_)
idem pour les 2 autres
JBW2p116
JBW2p244
