### ISSUE TITLE
Viele rose... mélodie indentique

### ISSUE THREAD

**Issue by BSCH67** [PhilJRS/dtars#27]
RSD5 Veile rose et RSD 1036 Mai revient sont pareils
M404 est à rapproché de RSD1099 Au coucou des bois

**Comment by PhilJRS** [comment]
RSD5=(RSD1036=m213)  OK, maj RSColl faite.
RSD1099=(m404=CDTS21)OK, maj RSColl faite.

**Comment by PhilJRS** [comment]
Fait.
