### ISSUE TITLE
RSD 1103

### ISSUE THREAD

**Issue by BSCH67** [PhilJRS/dtars#28]
RSD 1103 branle de ST ELME à rapprocher de CDTS 20

**Comment by PhilJRS** [comment]
En RSD1103 On reconnait la mélodie des épés m403, entière.  C'est validé, le RSColl est à jour.  Reste le gold à corriger.

**Comment by PhilJRS** [comment]
Fait

**Comment by PhilJRS** [comment]
DSepees=m403 ?

**Comment by PhilJRS** [comment]
done
