### ISSUE TITLE
RSD 1221

### ISSUE THREAD

**Issue by BSCH67** [PhilJRS/dtars#29]
RSD 1221 Scottisch-valse à rapprocher de Dampfwalzer RSD 741 Mel ?? mais surtout de Maria wollt Auswandern

**Comment by PhilJRS** [comment]
La RSD1221 n'a pas de mél asscociée, mais doit être associé à la mél 13 comme RSD741. Le gsheet RSColl est déjà à jour. Reste gold RS à updater

**Comment by PhilJRS** [comment]
Fait
