### ISSUE TITLE
comparer m402 et m57 (Niedsack) 

### ISSUE THREAD

**Issue by PhilJRS** [PhilJRS/dtars#34]
yadup! => Je propose de libérer m402 et de faire IKE1 = m57

Par ailleurs, dans niedsack.gdoc, il était écrit:
> Chorégraphie du groupe  Kochloeffel de Souffelweyersheim
> Chorégraphie Jean-Luc Neth
Tu parlais bien de la version IKE1, ou de celle (avec la fameuse vis de fin) pratiquée il y a 2 ans (?) avec les KL?

J'ai màj le m402 et mis les scans-choré de la musique musescorisée dans la fiche de danse

puis j'ai vu le doublon...

**Comment by BSCH67** [comment]
Oui il y a probablement doublon
Il faut recontextualisé. 1991 sur une musique de R Egles, l'IKE danse un medley de scottisch...Origine de la musique à retrouver.
M402 revoir commentaire : Egles ne chante pas.
Dans un second temps JL Neth propose une chorée pour les LEFFEL (vis sans fin...) Musique de R Egles, réécrite par JP probablement.
Question : devons-nous mettre cette chorée dans niedsack.gdoc ? ou celle de l'IKE ?
J'ai déjà commencer par clarifier le texte dans DS.
Pour le reste on statut lundi.

**Comment by PhilJRS** [comment]
1) à la question:"devons-nous mettre cette chorée dans niedsack.gdoc ? ou celle de l'IKE ?": la page "niedsack" du gsheet [Chorés DTA](https://docs.google.com/spreadsheets/d/1f6kw7O0k-PC9mftOqc3wck8__RmWEJh6iOTLHseBFL8/edit#gid=662756359) est désormais l'objet porte la référence unique "niedsack" dans la base DTA-RS.  Une DS n'est pas  "dans" une autre référence";. une DS pointe dans le gold (coll DS) vers une (ou des) mélodie(s) (m57 et m402 pour DSniedsack) , pas directement vers des documents comme IKE1.

2) Puisque tu viens d'ajouter du contenu -certes tout à fait valable- au .gdoc,  je l'ai de suite rapatrié dans le sheet [Chorés DTA](https://docs.google.com/spreadsheets/d/1f6kw7O0k-PC9mftOqc3wck8__RmWEJh6iOTLHseBFL8/edit#gid=662756359).  En effet,  les  gdocs de danses, sont abandonnés dans l'architecture de notre base, et ne doivent donc _plus être enrichis_, au profit de la page correspondante du gSheet DS. Au contraire, il faudra songer à les "nettoyer" (les 162!):  Je l'ai fait maintenant pour la DSniedsack:
- [ ] reverser le contenu -là où il reste d'actualité-  vers le tableau gSheet correspondant. 
- [ ] puis le .gdoc doit être effacé sur Google,
- [ ]  puis sa référence (en case A1 du tableau) définitivement effacée aussi de la case A1 du tableau.

On peut procéder par étapes. Mettre la priorité sur quelles DS??

**Comment by PhilJRS** [comment]
D'Niedsack, c'est désormais la m57 et rien d'autre, m402 est repris par RSD3 (et mis les coll RS,mais aussi JL, JBW à jour selon (https://dta.philiole.fr/Collections/RS/RSD3.jpg)
