### ISSUE TITLE
réfs de DTA76 non conformes: 33T ou CD?

### ISSUE THREAD

**Issue by PhilJRS** [PhilJRS/dtars#35]
Voir la colonne G de [Danses BS_PS: DTA](https://docs.google.com/spreadsheets/d/11NubiPX_OteUOumf10uhwvRorLeNyBtpoBfXNdYDiu0/edit#gid=1347246259)

**Comment by PhilJRS** [comment]
Je te laisse mettre à jour la colonne B de [Danses BS_PS: DTA](https://docs.google.com/spreadsheets/d/11NubiPX_OteUOumf10uhwvRorLeNyBtpoBfXNdYDiu0/edit#gid=1347246259) pour m'assurer que tu as vu...;)

**Comment by BSCH67** [comment]
Je valide que le 33T prend en compte 2 faces A et B si bien que la notation en col G est OK
Le CD propose une notation 1 à 14 C OK aussi.
Voir la photo envoyée.

**Comment by PhilJRS** [comment]
Tu as raison, (je remets BS_PS, mais surtout gold.DTA) à la position de départ.
