### ISSUE TITLE
mauvaise  m27,  au moins 4 musiques différentes s'y mélangent...

### ISSUE THREAD

**Issue by PhilJRS** [PhilJRS/dtars#36]
La mélodie de AU10a2 n'est pas la même que  AU40.17.  
Je doute aussi du titre ( jaquette de  AU10a2), certainement influencé par la DS heissa.kathrinele,
Vrais titres de mx2 , 3, 4, 5  à retrouver...
n.b. Les lignes qui suivent sont plus faciles à lire -et à écouter - sur https://editor.drawthedots.com/, il suffit de les recopier en bloc.

Q:3/8=80
T: m27 m101:
cGG G>FE | FED E3:: GGG G>FE :|FED E3|       % m101, JBW2P82,SA171, AU18A15
cGG G>FE | FED |1E3:|C3|:B,DB, CEG:|         % mx1 utilise et étend m101. (ZZCante3p446, RTF1.5 (Heissa))
E2G E2G | FED |1 A2G :|C                     % mx2 (pour AU10a2)
E>EE G>GG |FFF |1E/F/G/A/G :| E3             % mx3 (pour AU10a2 et (mx4 = AU40.17 et IKE15)
E|G2E F>ED | C2E EDC | D2F FED | E2G G2c|A2A A2c |G2G G2c | BAG GAB |c4 %mx4 (pour AU40.17=IKE15)
%mx4 = mx1+mx2+mx3
%m27' = mx4 + mx5

**Comment by BSCH67** [comment]
Effectivement c'est Heissa Kathrinele  la danse le dénominateur commun.
A savoir H K est équivalent à une voltée, les refrains valsées qui l'accompagnent sont multiples Il faut donc décrire chaque refrain.
AU10a2 E bure maidele màg i net - Hinterem Menchter - Hinterem Menchter seconde partie plaisir des dames
AU40.17 Hinterem Menchter seconde partie plaisir des dames- Hinterem Menchter
Titre à affiner.

**Comment by PhilJRS** [comment]
Super, merci! 
Je comprends : 
1) mx2 et mx3 sont en fait les 2 parties de la **m369** (RSD659 Hinterem Menchter == Plaisir des dames).
En regardant le graphe 353, je vois que m369 y a déjà pas mal de petits...( 370 , 380, 377, 381, 379) mais on n'avait pas vu ceux commis avec la "H K" :) . 
2) mx4 = **m354**  E bure maidele màg i net (aussi déjà parent de la m368 (donc aussi dans le graphe 353 )

Il reste donc 6 m -dont deux nouvellement isolées (mx1 et mx4, seront **m434** et **m435**) qui se dégagent pour décrire -les 2 variantes de musique pour la choré HK (l'une avec la m354, l'autre sans)

Q:3/8=80
T: m101, 434, 369, et 435 :
%
|: cGG G>FE | FED E3 :: GGG G>FE :|FED C3|]       
% m101 "Gügück" (JBW2P82,SA171, AU18A15)
%
|: cGG G>FE | FED |1 E3:|C3|:B,DB, CEG:|]
% m434 "Heissa" étend ainsi m101.1 (ZZCante3p446, RTF1.5)
%
E>EE G>GG |FFF |1E/F/G/A/G :| E3 |: E2G E2G | FED |1 A2G :|C3 |]
% m369 "Hinterm" (RSD659, ZZRomin5.183)
%
E|G2E F>ED | C2E EDC | D2F FED | E2G G2c|A2A A2c |G2G G2c | BAG GAB |c3|]
% m354 "Bürebiewala" (RSD312, JL2.11a, SA69, SA70)
%
% alors on peut re-définir m354 et m27':
%    m435 (AU10a2) = m434 + m369 
%    m27' (AU40.17, IKE15) = m435 + m354 

Il reste donc 6 m -dont deux nouvellement isolées (mx1 et mx4, seront **m434** et **m435**) qui se dégagent pour décrire -les 2 variantes de musique pour la choré HK (l'une avec la m354, l'autre sans)
