### ISSUE TITLE
Les titres de AU63 (33t En Alsace) non conformes 

### ISSUE THREAD

**Issue by PhilJRS** [PhilJRS/dtars#39]
La plupart des titres de AU63 (33t "En Alsace", une publication, d'où la règle qui s'applique) sont non-conformes car ils omettent la version alsacienne du titre ( cf la jaquette tiré des annexes sur WD DTA-RS/Annexes/AU Annexes
[AU63 jaquette.pdf](https://github.com/PhilJRS/dtars/files/15404139/AU63.jaquette.pdf)

Il faudrait faire un tour de tous les CD et disques publiés pour valider que nos titres sont bons.

**Comment by BSCH67** [comment]
J'ai fait un tour dans AUindex pour vérifier les titres AU. J'ai l'impression que tu es déjà intervenu sur certain titre. Donc tout va bien.

**Comment by PhilJRS** [comment]
fait
