### ISSUE TITLE
Le pont du Nord

### ISSUE THREAD

**Issue by BSCH67** [PhilJRS/dtars#44]
M66
Dans danses propres ce n'est pas un branle à 5 temps mais un branle à 6 temps.
Il faut changer  branle.a.5 en branle.a.6.

**Comment by BSCH67** [comment]
Je propose par la même occasion de "Killer" la danse pont.nord car redondant avec branle.a.6.
Pour M66 dans rubrique danses propres nous aurons : #branle, branle.a.6 (après correction)

**Comment by PhilJRS** [comment]
corrigé (m66= branle.a.6)
J'ai supprimmé le tab pont.nord dans le gsheet "Chorés DTA", mais le pont.nord.gdoc appartient à BS, je ne peux le supprimmer ... à toi de le faire

**Comment by BSCH67** [comment]
Le gdoc a été mis dans la poubelle par BSCH.
