### ISSUE TITLE
RSD736 et 737

### ISSUE THREAD

**Issue by BSCH67** [PhilJRS/dtars#48]
Dans DTA-RS je tape RSD736 ou 737  Virginie ou eau de vie réponse... 1 titre...pas de mel, pas de scan
Lorsque que je passe par le bouton  RS le scan et la mélodie existent. Il y a un soucis de report d'information !

**Comment by PhilJRS** [comment]
C'est normal, parce qu'aucune mél était encore associée à RSD736.
Corrigé: m436
